apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels: { app: hello }
spec:
  replicas: 2
  selector:
    matchLabels: { app: hello }
  template:
    metadata:
      labels: { app: hello }
    spec:
      containers:
        - name: hello
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector: { app: hello }
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
